# Generated by Django 2.2.2 on 2019-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("location", "0002_warehouse")]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="address",
            field=models.TextField(null=True, verbose_name="WareHouse Address"),
        ),
        migrations.AlterUniqueTogether(
            name="warehouse", unique_together={("name", "city")}
        ),
    ]
