# Generated by Django 2.2.2 on 2019-10-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("location", "0003_auto_20191024_0438")]

    operations = [
        migrations.AlterUniqueTogether(name="city", unique_together={("name", "state")})
    ]
