# Generated by Django 2.2.2 on 2019-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletproduct',
            name='color',
            field=models.CharField(default='white', max_length=254, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='outletproduct',
            name='color_code',
            field=models.CharField(default='#fff', max_length=254, verbose_name='Color Code'),
        ),
    ]
