# Generated by Django 2.2.2 on 2019-11-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("outlet", "0004_outletproduct_name")]

    operations = [
        migrations.AlterField(
            model_name="outlet",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="school.School",
                verbose_name="School",
            ),
        )
    ]
