# Generated by Django 2.2.2 on 2019-11-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0005_auto_20191103_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='outletsubproduct',
            name='size',
            field=models.CharField(choices=[('20', '20'), ('22', '22'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44')], default='24', max_length=4, verbose_name='Size'),
        ),
    ]
