exclude: .+/migrations/.+\.py
repos:
#-   repo: local
#    hooks:
#    - id: flake8
#      name: flake8
#      entry: flake8
#      language: python
#      files: \.py$
#      args: [max-line-length=88]
#      log_file: 'src/flake8.pycodestyle.log'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --ignore=F401]
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
