# Generated by Django 2.2.2 on 2019-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender_type",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=254,
                verbose_name="Gender",
            ),
        )
    ]
