# Generated by Django 2.2.2 on 2019-07-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Product Type'),
        ),
    ]
