# Generated by Django 2.2.2 on 2019-07-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("school", "0001_initial")]

    operations = [
        migrations.RenameField(model_name="school", old_name="lat", new_name="latitude")
    ]
