# Generated by Django 2.2.2 on 2019-10-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("school", "0005_auto_20191023_1306")]

    operations = [
        migrations.RemoveField(model_name="school", name="state"),
        migrations.AlterField(
            model_name="school",
            name="city",
            field=models.ForeignKey(
                help_text="School's Region",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.City",
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                max_length=5,
                verbose_name="Section",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="standard",
            field=models.CharField(
                choices=[
                    ("I", "I"),
                    ("II", "II"),
                    ("III", "III"),
                    ("IV", "IV"),
                    ("V", "V"),
                    ("VI", "VI"),
                    ("VII", "VII"),
                    ("VIII", "VIII"),
                    ("IX", "IX"),
                    ("X", "X"),
                    ("XI", "XI"),
                    ("XII", "XII"),
                ],
                max_length=5,
                verbose_name="Class",
            ),
        ),
    ]
