# Generated by Django 2.2.2 on 2019-07-17 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Create Date/Time"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date/Time Modified"
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="Name")),
                ("box_code", models.CharField(max_length=10, verbose_name="Box code")),
                (
                    "female_items",
                    models.IntegerField(verbose_name="Number of female Items"),
                ),
                (
                    "male_items",
                    models.IntegerField(verbose_name="Number of Male Items"),
                ),
                ("total_item", models.IntegerField(verbose_name="Total Items")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Box", "verbose_name_plural": "Boxes"},
        ),
        migrations.CreateModel(
            name="IndentRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Create Date/Time"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date/Time Modified"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="school.School"
                    ),
                ),
            ],
            options={
                "verbose_name": "Indent Request",
                "verbose_name_plural": "Indent Requests",
            },
        ),
        migrations.CreateModel(
            name="IndentRequestDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Create Date/Time"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date/Time Modified"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity Required")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indent_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock_order.IndentRequest",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indent Request Detail",
                "verbose_name_plural": "Indent Request Details",
            },
        ),
        migrations.CreateModel(
            name="Indent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Create Date/Time"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date/Time Modified"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Indent Name")),
                ("num_of_boxes", models.IntegerField(verbose_name="Number of Boxes")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "shipping_from",
                    models.CharField(max_length=254, verbose_name="Shipping From"),
                ),
                (
                    "shipping_from_lat",
                    models.CharField(
                        max_length=20, verbose_name="Shipping from Latitude"
                    ),
                ),
                (
                    "shipping_from_long",
                    models.CharField(
                        max_length=20, verbose_name="Shipping from Longitude"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indent_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock_order.IndentRequest",
                    ),
                ),
                (
                    "shipping_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="school.School"
                    ),
                ),
            ],
            options={"verbose_name": "Indent", "verbose_name_plural": "Indents"},
        ),
        migrations.CreateModel(
            name="BoxItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Create Date/Time"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date/Time Modified"
                    ),
                ),
                ("num_of_item", models.IntegerField(verbose_name="Number of Items")),
                ("item_scanned", models.IntegerField(verbose_name="Item Scanned")),
                ("item_in_shelf", models.IntegerField(verbose_name="Items in shelf")),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock_order.Box",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.Product",
                    ),
                ),
            ],
            options={"verbose_name": "Box Item", "verbose_name_plural": "Box Items"},
        ),
        migrations.AddField(
            model_name="box",
            name="indent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="stock_order.Indent"
            ),
        ),
    ]
