# Generated by Django 2.2.2 on 2019-07-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_order', '0003_auto_20190722_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indentrequestdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.OutletSubProduct'),
        ),
    ]
