# Generated by Django 2.2.2 on 2019-08-08 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("stock_order", "0003_auto_20190722_1014")]

    operations = [
        migrations.RemoveField(model_name="indent", name="num_of_boxes"),
        migrations.AddField(
            model_name="indent",
            name="received_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Received On",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indent",
            name="shipped_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Shipped On"
            ),
            preserve_default=False,
        ),
    ]
