# Generated by Django 2.2.2 on 2019-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_order', '0004_auto_20190723_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxitem',
            name='item_in_shelf',
            field=models.IntegerField(default=0, verbose_name='Item in Shelf'),
        ),
    ]
