# Generated by Django 2.2.2 on 2019-08-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stock_order", "0005_auto_20190808_0802")]

    operations = [
        migrations.AlterModelOptions(
            name="indentrequest",
            options={
                "verbose_name": "Indent Request",
                "verbose_name_plural": "Indent Request",
            },
        ),
        migrations.RemoveField(model_name="box", name="total_item"),
        migrations.AlterField(
            model_name="boxitem",
            name="item_scanned",
            field=models.IntegerField(default=0, verbose_name="Item Scanned"),
        ),
        migrations.AlterField(
            model_name="boxitem",
            name="num_of_item",
            field=models.IntegerField(verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="indent",
            name="received_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Received On"
            ),
        ),
    ]
