# Generated by Django 2.2.2 on 2019-10-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_auto_20191024_0504"),
        ("stock_order", "0006_auto_20190808_0845"),
    ]

    operations = [
        migrations.RemoveField(model_name="indent", name="shipping_from"),
        migrations.AddField(
            model_name="indent",
            name="warehouse_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.WareHouse",
                verbose_name="Shipping From",
            ),
        ),
    ]
