# Generated by Django 2.2.2 on 2019-10-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("stock_order", "0007_auto_20191024_0544")]

    operations = [
        migrations.RemoveField(model_name="indent", name="shipping_from_lat"),
        migrations.RemoveField(model_name="indent", name="shipping_from_long"),
        migrations.AlterField(
            model_name="indent",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.School",
                verbose_name="School",
            ),
        ),
        migrations.AlterField(
            model_name="indent",
            name="shipped_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Shipped On"),
        ),
    ]
