# Generated by Django 2.2.2 on 2019-11-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stock_order", "0012_auto_20191105_1147")]

    operations = [
        migrations.RemoveField(model_name="indent", name="outlet"),
        migrations.AddField(
            model_name="boxitem",
            name="warehouse_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
