# Generated by Django 2.2.2 on 2019-10-24 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="value",
            field=models.IntegerField(
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Value",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.PositiveIntegerField(verbose_name="Discount"),
        ),
        migrations.AlterField(
            model_name="suborder",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Amount",
            ),
        ),
    ]
