# Generated by Django 2.2.2 on 2019-07-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.OutletSubProduct',
                                    verbose_name='Outlet Product'),
        ),
    ]
