# Generated by Django 2.2.2 on 2019-11-03 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("manager", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        )
    ]
